apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rasa-chatbot
  template:
    metadata:
      labels:
        app: rasa-chatbot
    spec:
      containers:
        - name: rasa-chatbot
          image: dejain4/rasa-chatbot:latest
          ports:
            - containerPort: 5005
